version: "3"
services:

    redis:
        image: redis:alpine
        ports:
            - "6379"

    node1:
        image: shared_database:latest
        ports:
            - "0.0.0.0:8080:8080"
        environment:
            - NODE_NAME=node1
            - WEBAPI_PORT=8080
            - REDIS_SETTINGSTORE=redis://redis/0
            - REDIS_DATASTORE=redis://redis/1
        command: python run.py
        volumes:
            - ./:/shared_database:ro
        links:
            - redis
        depends_on:
            - redis

    node2:
        image: shared_database:latest
        ports:
            - "0.0.0.0:8081:8081"
        environment:
            - NODE_NAME=node2
            - WEBAPI_PORT=8081
            - REDIS_SETTINGSTORE=redis://redis/0
            - REDIS_DATASTORE=redis://redis/2
        command: python run.py
        volumes:
            - ./:/shared_database:ro
        links:
            - redis
            - node1
        depends_on:
            - redis
